<!DOCTYPE html>
<html lang="id">
<head>
    <meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Panduan mencari informasi bus dari Terminal Purabaya Bungurasih."><title>Panduan | PURABAYA GO</title>
    <link rel="stylesheet" href="<?= base_url('css/home.css') ?>">
    <style>
        .guide-page{background:#f4f7fb;min-height:100vh}.guide-hero{background:#092c45;color:#fff;padding:82px 0 90px}.guide-hero h1{font-size:clamp(2.2rem,5vw,4.5rem);margin:12px 0}.guide-hero p{max-width:650px;color:#c9dce5;line-height:1.7}.guide-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:-40px;position:relative}.guide-card{background:#fff;border-radius:16px;padding:25px;box-shadow:0 12px 28px rgba(9,44,69,.08);border:1px solid #e4edf1}.guide-number{display:inline-grid;place-items:center;width:34px;height:34px;border-radius:10px;background:#f2b63b;color:#092c45;font-weight:900}.guide-card h2{margin:16px 0 8px;color:#092c45;font-size:1.2rem}.guide-card p,.guide-card li{color:#58707d;line-height:1.7}.guide-card ul{padding-left:20px}.guide-notice{margin-top:24px;padding:20px;border-radius:14px;background:#fff5dc;border:1px solid #f0cf7a;color:#654d12;line-height:1.7}.guide-notice strong{color:#9b6500}.guide-footer{padding:48px 0;color:#607784}@media(max-width:680px){.guide-grid{grid-template-columns:1fr}.guide-hero{padding:56px 0 75px}}
    </style>
</head>
<body>
<header class="site-nav"><div class="nav-inner"><a class="brand" href="<?= site_url('/') ?>"><span class="brand-mark">P</span> PURABAYA GO</a><button class="menu-toggle" type="button" aria-expanded="false" aria-controls="guide-navigation">Menu</button><nav class="nav-links" id="guide-navigation"><a href="<?= site_url('/') ?>">Home</a><a href="<?= site_url('search') ?>">Cari Bus</a><a href="<?= site_url('destinations') ?>">Tujuan</a><a class="active" href="<?= site_url('guide') ?>">Guide</a><a href="<?= site_url('about') ?>">About</a><?php if (session()->get('logged_in')): ?><a href="<?= site_url('logout') ?>">Logout</a><?php else: ?><a href="<?= site_url('login') ?>">Login</a><a href="<?= site_url('register') ?>">Register</a><?php endif; ?></nav></div></header>
<main class="guide-page"><section class="guide-hero"><div class="section-inner"><span class="eyebrow">PANDUAN PURABAYA GO</span><h1>Temukan informasi bus dengan lebih cepat.</h1><p>Gunakan PURABAYA GO untuk membaca tujuan, operator, shelter, estimasi tarif, dan jadwal keberangkatan dari Terminal Purabaya/Bungurasih.</p></div></section><section class="section"><div class="section-inner"><div class="guide-grid"><article class="guide-card"><span class="guide-number">01</span><h2>Pilih tujuan atau cari nama bus</h2><p>Buka menu <strong>Cari Bus</strong>, lalu ketik kota tujuan atau nama operator seperti Malang, Bagong, atau Sugeng Rahayu.</p></article><article class="guide-card"><span class="guide-number">02</span><h2>Gunakan filter yang relevan</h2><p>Saring hasil berdasarkan Ekonomi, Patas, Eksekutif, shelter, tarif, atau waktu keberangkatan.</p></article><article class="guide-card"><span class="guide-number">03</span><h2>Baca card layanan</h2><p>Setiap card merangkum tujuan, operator, shelter, tarif, jadwal, frekuensi, dan status jadwal.</p></article><article class="guide-card"><span class="guide-number">04</span><h2>Periksa detail sebelum berangkat</h2><p>Buka <strong>Lihat Detail</strong> untuk membaca daftar operator, jadwal lengkap, catatan, dan informasi keberangkatan.</p></article><article class="guide-card"><span class="guide-number">05</span><h2>Pahami status jadwal</h2><ul><li><strong>Jadwal tersedia:</strong> waktu tercatat secara spesifik.</li><li><strong>Perkiraan jadwal:</strong> waktu dapat berubah sesuai operasional.</li><li><strong>Operasional fleksibel:</strong> berangkat menyesuaikan ketersediaan bus.</li></ul></article><article class="guide-card"><span class="guide-number">06</span><h2>Kenali area keberangkatan</h2><p>Catat nomor shelter yang tampil. Tanyakan kembali kepada petugas terminal bila posisi bus atau jalur keberangkatan berubah.</p></article></div><div class="guide-notice"><strong>INFORMASI KEAMANAN</strong><br>Purabaya Go adalah portal informasi, bukan layanan pemesanan atau pembayaran tiket. Pastikan memilih dan membayar melalui loket/operator resmi, serta waspada terhadap calo.</div><div class="guide-notice"><strong>DATA PROTOTYPE</strong><br>Jadwal dan tarif merupakan informasi prototype untuk kebutuhan akademik/demo, bukan data real-time resmi.</div></div></section></main><footer class="footer guide-footer"><div class="section-inner footer-inner"><div><strong>PURABAYA GO</strong><p>Temukan Busmu, Mulai Perjalananmu.</p></div><small>Portal informasi keberangkatan bus dari Terminal Purabaya.</small></div></footer><script>const t=document.querySelector('.menu-toggle'),n=document.querySelector('.nav-links');t?.addEventListener('click',()=>{const o=n.classList.toggle('is-open');t.setAttribute('aria-expanded',String(o))});</script>
</body></html>
